on: push
jobs:
  update:
    runs-on: ubuntu-lates
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          
      - name: Install Databricks CLI 
        run: | 
          python -m pip install --upgrade databricks-cli
          
      - name: Remote update Prod Repo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICS_TOKEN: ${{ secrets.DATABRICS_TOKEN }}
        run: |
          databricks repos update --branch main --path /Repos/Prod/db_test_repo
